### ISSUE TITLE
[roq-data] raw array content as object not working out of the box

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-roq#147]
there is a bug for a raw data array, when iterating, it doesn't wrap items content as JsonObject, it works with an extra items layer:

This works:
```yml
items:
  - title: "Blog"
    url: "/"
    icon: "fa fa-newspaper-o"
  - title: "Documentation"
    url: "https://docs.quarkiverse.io/quarkus-roq/dev/index.html"
    icon: "fa fa-book"
    target: "_blank"
  - title: "Events"
    url: "events"
    icon: "fa fa-calendar"
  - title: "About"
    url: "about"
    icon: "fa fa-thumbs-up"
```

this doesn't (when used from qute in a for loop):
```yml

- title: "Blog"
  url: "/"
  icon: "fa fa-newspaper-o"
- title: "Documentation"
  url: "https://docs.quarkiverse.io/quarkus-roq/dev/index.html"
  icon: "fa fa-book"
  target: "_blank"
- title: "Events"
  url: "events"
  icon: "fa fa-calendar"
- title: "About"
  url: "about"
  icon: "fa fa-thumbs-up"
```
