### ISSUE TITLE
[roq-data] Generated bindings to data file

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-roq#19]
The goal is to have the records generated some way. TBD

**Comment by maxandersen** [comment]
as seen in example #19 yaml with this:

```
categories:
  - category: Core
    cat-id: core
    extensions:
      - name: Configuration
        description: "Included: MicroProfile Configuration via SmallRye"
      - name: Logging
        description: "Included: centralized log management for Quarkus"
      - name: ArC
        description: "Build time CDI dependency injection"
        labels:
        - arc
        - cdi
        - dependency-injection
        - di
        groupId: io.quarkus
        artifactId: quarkus-arc
  - category: Web
    cat-id: web
    extensions:
      - name: Netty
        description: "Netty is a non-blocking I/O client-server framework. Used by Quarkus as foundation layer."
        groupId: io.quarkus
        artifactId: quarkus-netty
      - name: RESTEasy JAX-RS
        description: "REST framework implementing JAX-RS and more"
        labels:
        - resteasy
        - jaxrs
        - web
        - rest
        groupId: io.quarkus
        artifactId: quarkus-resteasy
```

could be:

```
record Categories(
    List<Category> categories
) {}

record Category(
    String category,
    @JsonProperty("cat-id") String catId,
    List<Extension> extensions
) {}

record Extension(
    @JsonProperty("name") String name,
    @JsonProperty("description") String description,
    @JsonProperty("labels") List<String> labels,
    @JsonProperty("groupId") Optional<String> groupId,
    @JsonProperty("artifactId") Optional<String> artifactId
) {}
```

that would be the generation - but imagine also that user can write the above and have that validated against the data as seen in #18.
