### ISSUE TITLE
Show generic avatar when there is no one

### ISSUE THREAD

**Issue by mcruzdev** [quarkiverse/quarkus-roq#497]
Having in mind a valid author item:

```yaml
roqqy:
  name: "Matheus Cruz"
  job: OpenSourcerer
  nickname: mcruzdev
  profile: "https://github.com/mcruzdev"
  avatar: "https://raw.githubusercontent.com/quarkiverse/quarkus-roq/refs/heads/main/blog/public/images/iamroq.png"
  bio: |
    Quarkus is my go-to framework for making Java development not only faster but more fun. 
    I’m driven by the mission to create high-performance, lightweight microservices that scale effortlessly in the cloud. 
    With Quarkus, I can push Java to its limits, and nothing excites me more than exploring new ways to optimize and streamline applications with this amazing toolkit.
```

when the avatar is not set, it would be great if we generate a default one.
